SDK-2600 remove xhprof from requirements
spryker/profiler pull request #1
Opened 2023-06-19 09:25 UTC by sergeyspryker

## PR Description
https://spryker.atlassian.net/browse/SDK-2600
TBD

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2023-06-20 08:12 UTC, pavelmaksimov25 approved these changes

2023-06-20 08:46 UTC, vol4onok approved these changes

2023-06-20 13:00 UTC, tolerants requested changes

2023-06-20 13:00 UTC, tolerants commented on src/Spryker/Yves/Profiler/Theme/default/profiler.html.twig
> +    {% if collector.profilerData.isXhprofExtensionEnabled %}
Can `collector` and `collector.profilerData` be empty? If yes suggest to add additional check. Please check it in other places.

2023-06-20 17:37 UTC, sergeyspryker commented on src/Spryker/Yves/Profiler/Theme/default/profiler.html.twig
> +    {% if collector.profilerData.isXhprofExtensionEnabled %}
<transfer name="ProfilerData">
        <property name="content" type="string"/>
        <property name="stats" type="array" singular="statsItem"/>
        <property name="type" type="string"/>
        <property name="isXhprofExtensionEnabled" type="bool"/>
    </transfer>

2023-06-20 17:53 UTC, tolerants approved these changes
FE part looks good.

2023-06-27 10:59 UTC, floriankraemer commented
@sergeyspryker can you change the title to `SDK-2600 Removed xhprof from the requirements.` I can't change it due to a lack of permissions for this repository.

2023-06-27 11:06 UTC, merged